version: '3'

services:
  web:
    build: 
      context: .
    container_name: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  
  db:
    image: mongo
    container_name: db